# Generated by Django 5.2.2 on 2025-06-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_alter_post_post_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_fixed",
            field=models.BooleanField(default=False),
        ),
    ]
