# Generated by Django 5.2.2 on 2025-06-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_add_is_fixed"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
