# Generated by Django 5.2.2 on 2025-06-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_customuser_last_message_read_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="isAdmin",
            field=models.BooleanField(default=False),
        ),
    ]
