# Generated by Django 5.2.2 on 2025-06-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_add_isAdmin"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="exp",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
